defaults: &defaults
  host: 192.168.1.35
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  database: liberty_development

test:
  <<: *defaults
  database: pembaca_test

production:
  <<: *defaults
  host: localhost
  database: pembaca_production